export const itags = {
    5: { itag: 5, format: 'flv', content: 'audio/video', quality: '240p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    6: { itag: 6, format: 'flv', content: 'audio/video', quality: '270p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    17: { itag: 17, format: '3gp', content: 'audio/video', quality: '144p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    18: { itag: 18, format: 'mp4', content: 'audio/video', quality: '360p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    22: { itag: 22, format: 'mp4', content: 'audio/video', quality: '720p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    34: { itag: 34, format: 'flv', content: 'audio/video', quality: '360p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    35: { itag: 35, format: 'flv', content: 'audio/video', quality: '480p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    36: { itag: 36, format: '3gp', content: 'audio/video', quality: '180p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    37: { itag: 37, format: 'mp4', content: 'audio/video', quality: '1080p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    38: { itag: 38, format: 'mp4', content: 'audio/video', quality: '3072p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    43: { itag: 43, format: 'webm', content: 'audio/video', quality: '360p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    44: { itag: 44, format: 'webm', content: 'audio/video', quality: '480p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    45: { itag: 45, format: 'webm', content: 'audio/video', quality: '720p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    46: { itag: 46, format: 'webm', content: 'audio/video', quality: '1080p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    82: { itag: 82, format: 'mp4', content: 'audio/video', quality: '360p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    83: { itag: 83, format: 'mp4', content: 'audio/video', quality: '480p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    84: { itag: 84, format: 'mp4', content: 'audio/video', quality: '720p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    85: { itag: 85, format: 'mp4', content: 'audio/video', quality: '1080p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    92: { itag: 92, format: 'hls', content: 'audio/video', quality: '240p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    93: { itag: 93, format: 'hls', content: 'audio/video', quality: '360p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    94: { itag: 94, format: 'hls', content: 'audio/video', quality: '480p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    95: { itag: 95, format: 'hls', content: 'audio/video', quality: '720p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    96: { itag: 96, format: 'hls', content: 'audio/video', quality: '1080p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    100: { itag: 100, format: 'webm', content: 'audio/video', quality: '360p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    101: { itag: 101, format: 'webm', content: 'audio/video', quality: '480p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    102: { itag: 102, format: 'webm', content: 'audio/video', quality: '720p', bitrate: '', range: '', is3D: 1, hdr: 0, disp: '', type: 'Video' },
    132: { itag: 132, format: 'hls', content: 'audio/video', quality: '240p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    133: { itag: 133, format: 'mp4', content: 'video', quality: '240p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    134: { itag: 134, format: 'mp4', content: 'video', quality: '360p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    135: { itag: 135, format: 'mp4', content: 'video', quality: '480p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    136: { itag: 136, format: 'mp4', content: 'video', quality: '720p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    137: { itag: 137, format: 'mp4', content: 'video', quality: '1080p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    138: { itag: 138, format: 'mp4', content: 'video', quality: '2160p60', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    139: { itag: 139, format: 'm4a', content: 'audio', quality: '-', bitrate: '48k', range: '', is3D: 0, hdr: 0, disp: 'Only Audio', type: 'Audio' },
    140: { itag: 140, format: 'm4a', content: 'audio', quality: '-', bitrate: '128k', range: '', is3D: 0, hdr: 0, disp: 'Only Audio', type: 'Audio' },
    141: { itag: 141, format: 'm4a', content: 'audio', quality: '-', bitrate: '256k', range: '', is3D: 0, hdr: 0, disp: 'Only Audio', type: 'Audio' },
    151: { itag: 151, format: 'hls', content: 'audio/video', quality: '72p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: '', type: 'Video' },
    160: { itag: 160, format: 'mp4', content: 'video', quality: '144p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    167: { itag: 167, format: 'webm', content: 'video', quality: '360p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    168: { itag: 168, format: 'webm', content: 'video', quality: '480p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    169: { itag: 169, format: 'webm', content: 'video', quality: '1080p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    171: { itag: 171, format: 'webm', content: 'audio', quality: '-', bitrate: '128k', range: '', is3D: 0, hdr: 0, disp: 'Only Audio', type: 'Audio' },
    218: { itag: 218, format: 'webm', content: 'video', quality: '480p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    219: { itag: 219, format: 'webm', content: 'video', quality: '144p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    242: { itag: 242, format: 'webm', content: 'video', quality: '240p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    243: { itag: 243, format: 'webm', content: 'video', quality: '360p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    244: { itag: 244, format: 'webm', content: 'video', quality: '480p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    245: { itag: 245, format: 'webm', content: 'video', quality: '480p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    246: { itag: 246, format: 'webm', content: 'video', quality: '480p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    247: { itag: 247, format: 'webm', content: 'video', quality: '720p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    248: { itag: 248, format: 'webm', content: 'video', quality: '1080p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    249: { itag: 249, format: 'webm', content: 'audio', quality: '-', bitrate: '50k', range: '', is3D: 0, hdr: 0, disp: 'Only Audio', type: 'Audio' },
    250: { itag: 250, format: 'webm', content: 'audio', quality: '-', bitrate: '70k', range: '', is3D: 0, hdr: 0, disp: 'Only Audio', type: 'Audio' },
    251: { itag: 251, format: 'webm', content: 'audio', quality: '-', bitrate: '160k', range: '', is3D: 0, hdr: 0, disp: 'Only Audio', type: 'Audio' },
    264: { itag: 264, format: 'mp4', content: 'video', quality: '1440p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    266: { itag: 266, format: 'mp4', content: 'video', quality: '2160p60', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    271: { itag: 271, format: 'webm', content: 'video', quality: '1440p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    272: { itag: 272, format: 'webm', content: 'video', quality: '4320p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    278: { itag: 278, format: 'webm', content: 'video', quality: '144p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    298: { itag: 298, format: 'mp4', content: 'video', quality: '720p60', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    299: { itag: 299, format: 'mp4', content: 'video', quality: '1080p60', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    302: { itag: 302, format: 'webm', content: 'video', quality: '720p60', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    303: { itag: 303, format: 'webm', content: 'video', quality: '1080p60', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    308: { itag: 308, format: 'webm', content: 'video', quality: '1440p60', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    313: { itag: 313, format: 'webm', content: 'video', quality: '2160p', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    315: { itag: 315, format: 'webm', content: 'video', quality: '2160p60', bitrate: '', range: '', is3D: 0, hdr: 0, disp: 'Only Video', type: 'Video' },
    330: { itag: 330, format: 'webm', content: 'video', quality: '144p60', bitrate: '', range: '', is3D: 0, hdr: 1, disp: 'Only Video', type: 'Video' },
    331: { itag: 331, format: 'webm', content: 'video', quality: '240p60', bitrate: '', range: '', is3D: 0, hdr: 1, disp: 'Only Video', type: 'Video' },
    332: { itag: 332, format: 'webm', content: 'video', quality: '360p60', bitrate: '', range: '', is3D: 0, hdr: 1, disp: 'Only Video', type: 'Video' },
    333: { itag: 333, format: 'webm', content: 'video', quality: '480p60', bitrate: '', range: '', is3D: 0, hdr: 1, disp: 'Only Video', type: 'Video' },
    334: { itag: 334, format: 'webm', content: 'video', quality: '720p60', bitrate: '', range: '', is3D: 0, hdr: 1, disp: 'Only Video', type: 'Video' },
    335: { itag: 335, format: 'webm', content: 'video', quality: '1080p60', bitrate: '', range: '', is3D: 0, hdr: 1, disp: 'Only Video', type: 'Video' },
    336: { itag: 336, format: 'webm', content: 'video', quality: '1440p60', bitrate: '', range: '', is3D: 0, hdr: 1, disp: 'Only Video', type: 'Video' },
    337: { itag: 337, format: 'webm', content: 'video', quality: '2160p60', bitrate: '', range: '', is3D: 0, hdr: 1, disp: 'Only Video', type: 'Video' },
}